import nbformat as nbf

# Read existing notebook
with open('Data_Visualization.ipynb', 'r', encoding='utf-8') as f:
    nb = nbf.read(f, as_version=4)

# 1. Correlation Heatmap
nb.cells.append(nbf.v4.new_markdown_cell("## 6. Ma trận tương quan (Correlation Heatmap) doanh thu các khu vực\n**Mô tả phân tích:** Biểu đồ Heatmap dưới đây đo lường mức độ tương quan (chạy từ -1 đến 1) giữa doanh số của các thị trường khác nhau.\n- **Bắc Mỹ (NA) và Châu Âu (EU):** Có mức độ tương quan dương rất cao (đạt 0.77). Điều này có nghĩa là một tựa game thành công ở Bắc Mỹ thì khả năng rất cao cũng sẽ bán rất chạy ở Châu Âu do sự tương đồng lớn về văn hóa và thị hiếu.\n- **Nhật Bản (JP) so với phần còn lại:** Mức độ tương quan giữa thị trường Nhật Bản với NA và EU thấp hơn hẳn (chỉ ở mức ~0.45). Thị hiếu của game thủ Nhật Bản rất đặc thù (chuộng game Role-Playing, game nội địa), do đó một tựa game \"hot\" ở phương Tây chưa chắc đã thành công tại Nhật Bản, và ngược lại."))
nb.cells.append(nbf.v4.new_code_cell("sales_cols = ['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']\ncorrelation_matrix = df[sales_cols].corr()\n\nplt.figure(figsize=(10, 8))\nsns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=0.5, vmin=0, vmax=1)\nplt.title('Ma trận tương quan doanh thu giữa các thị trường', fontsize=16, fontweight='bold')\nplt.show()"))

# 2. Scatter Plot NA vs EU
nb.cells.append(nbf.v4.new_markdown_cell("## 7. Mối liên hệ doanh số giữa Bắc Mỹ và Châu Âu (Scatter Plot)\n**Mô tả phân tích:** Để làm rõ hơn mối tương quan tuyến tính chặt chẽ giữa thị trường Bắc Mỹ và Châu Âu (đã phát hiện ở Heatmap), ta sử dụng biểu đồ phân tán (Scatter Plot). \n- Đa số các điểm dữ liệu (đại diện cho các tựa game) nằm bám sát theo một đường chéo dốc lên. Khi doanh số Bắc Mỹ tăng, doanh số Châu Âu cũng có xu hướng tăng theo tỉ lệ thuận.\n- Tuy nhiên, vẫn có một số \"outliers\" (điểm dị biệt) nằm xa cụm dữ liệu chung – đó có thể là các tựa game được thiết kế đặc biệt nhắm riêng vào văn hóa Mỹ (ví dụ game Bóng bầu dục - Madden NFL) nên bán cực chạy ở Bắc Mỹ nhưng lại ế ẩm ở Châu Âu."))
nb.cells.append(nbf.v4.new_code_cell("plt.figure(figsize=(12, 7))\n# Bỏ qua vài game ngoại lệ quá khổng lồ (như Wii Sports) để quan sát rõ hơn xu hướng chung\nsns.scatterplot(data=df[df['Global_Sales'] < 30], x='NA_Sales', y='EU_Sales', alpha=0.6, color='purple', edgecolor=None)\n\n# Thêm đường xu hướng tuyến tính (trendline)\nsns.regplot(data=df[df['Global_Sales'] < 30], x='NA_Sales', y='EU_Sales', scatter=False, color='red', line_kws={\"linewidth\": 2})\n\nplt.title('Phân tán doanh thu: Bắc Mỹ (NA) vs Châu Âu (EU)', fontsize=16, fontweight='bold')\nplt.xlabel('Doanh thu Bắc Mỹ (Triệu bản)', fontsize=12)\nplt.ylabel('Doanh thu Châu Âu (Triệu bản)', fontsize=12)\nplt.show()"))

# 3. Stacked Bar Chart for Top 10 Games
nb.cells.append(nbf.v4.new_markdown_cell("## 8. Cấu trúc doanh thu theo khu vực của Top 10 tựa game vĩ đại nhất\n**Mô tả phân tích:** Biểu đồ cột chồng (Stacked Bar Chart) dưới đây \"mổ xẻ\" doanh thu toàn cầu của 10 tựa game bán chạy nhất lịch sử thành các khối nhỏ tương ứng với đóng góp của từng thị trường.\n- Nhìn chung, thị trường Bắc Mỹ (khối màu cam/xanh) luôn là trụ cột đóng góp nhiều nhất vào sự vĩ đại của các tựa game này (đặc biệt là Wii Sports).\n- Điểm thú vị là tựa game **Pokemon Red/Pokemon Blue** có khối thị phần của Nhật Bản cực kỳ lớn, ngang ngửa Bắc Mỹ và vượt xa Châu Âu. Điều này phản ánh rõ nguồn gốc phát triển của Pokemon và cơn sốt văn hóa tại Nhật Bản vào những năm 90."))
nb.cells.append(nbf.v4.new_code_cell("top_10_games = df.head(10)\n\n# Vẽ stacked bar bằng thư viện pandas base matplotlib\nax = top_10_games.set_index('Name')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].plot(\n    kind='bar', stacked=True, figsize=(14, 8), colormap='Set2', edgecolor='black'\n)\n\nplt.title('Cấu trúc doanh thu theo khu vực của Top 10 Game bán chạy nhất', fontsize=16, fontweight='bold')\nplt.xlabel('Tên Game', fontsize=12)\nplt.ylabel('Doanh thu (Triệu bản)', fontsize=12)\nplt.legend(title='Khu vực', fontsize=11, title_fontsize=12)\nplt.xticks(rotation=45, ha='right')\nplt.tight_layout()\nplt.show()"))

# Pairplot (Tổng quan quan hệ nhiều biến)
nb.cells.append(nbf.v4.new_markdown_cell("## 9. Tương quan tổng thể đa chiều (Pairplot)\n**Mô tả phân tích:** Biểu đồ Pairplot giúp cái nhìn bao quát về mối quan hệ của tất cả các biến doanh thu cùng lúc. \n- Đường chéo chính (KDE) thể hiện phân phối dữ liệu của từng khu vực, hầu hết đều lệch phải cực nặng (nghĩa là số lượng game bán được ít chiếm đa số tuyệt đối, chỉ một số rất ít game đạt doanh thu bom tấn).\n- Các biểu đồ phân tán phía dưới cho ta thấy không chỉ NA-EU có tương quan mạnh, mà Other_Sales (Khu vực khác) cũng có mối quan hệ tuyến tính khá rõ nét với các thị trường phương Tây, trong khi JP_Sales luôn phân bổ rời rạc so với phần còn lại."))
nb.cells.append(nbf.v4.new_code_cell("plt.figure(figsize=(12, 12))\n# Lấy mẫu một phần nhỏ dữ liệu để pairplot chạy nhanh và dễ nhìn (lấy top 1000 game doanh thu cao)\nsns.pairplot(df.head(1000)[sales_cols], diag_kind='kde', plot_kws={'alpha': 0.6, 'edgecolor': None}, height=2.5)\nplt.suptitle('Mối liên hệ đa chiều giữa doanh số các khu vực (Top 1000 Game)', y=1.02, fontsize=16, fontweight='bold')\nplt.show()"))


with open('Data_Visualization.ipynb', 'w', encoding='utf-8') as f:
    nbf.write(nb, f)
